programs: assignment2

assignment2 : assignment2.cpp
	g++ -std=c++0x -o assignment2 assignment2.cpp -pthread
	@echo Compilation Successful!

clean: 
	rm assignment2
	@echo All programs removed. Compile again.
	
